export const SELECT_CARS_BY_CATEGORY = "SELECT_CARS_BY_CATEGORY";
export const SELECT_ALL_CARS = "SELECT_ALL_CARS";
export const SORT_BY_PRICE_ASC = "SORT_BY_PRICE_ASC";
export const SORT_BY_PRICE_DESC = "SORT_BY_PRICE_DESC";
export const SORT_BY_DATE = "SORT_BY_DATE";
